baseURL = "https://trainopia.netlify.app"
disableLanguages = []
disqusShortname = "trainopia"
paginate = "6"
summaryLength = "10"
theme = "educenter-hugo"
themesDir = "../.."
defaultContentLanguageInSubdir = true
DefaultContentLanguage = "ar"

[Languages.en]
contentDir = "content/english"
copyright = "Copyright &copy; 2020 a hugo theme by [themefisher](https://themefisher.com)"
home = "Home"
languageCode = "en-us"
languageName = "En"
weight = 2
title = "Trainopia"

[[Languages.en.menu.footer]]
name = "teacher"
url = "teacher"
[[Languages.en.menu.footer]]
name = "notice"
url = "notice"
[[Languages.en.menu.footer]]
name = "event"
url = "event"
[[Languages.en.menu.footer]]
name = "scholarship"
url = "scholarship"
[[Languages.en.menu.footer]]
name = "research"
url = "research"
[[Languages.en.menu.main]]
name = "About"
url = "about"
weight = 1
[[Languages.en.menu.main]]
name = "course"
url = "course"
weight = 2
[[Languages.en.menu.main]]
hasChildren = true
name = "Pages"
weight = 3
[[Languages.en.menu.main]]
name = "teacher"
parent = "Pages"
url = "teacher"
[[Languages.en.menu.main]]
name = "notice"
parent = "Pages"
url = "notice"
[[Languages.en.menu.main]]
name = "event"
parent = "Pages"
url = "event"
[[Languages.en.menu.main]]
name = "scholarship"
parent = "Pages"
url = "scholarship"
[[Languages.en.menu.main]]
name = "research"
parent = "Pages"
url = "research"
[[Languages.en.menu.main]]
name = "blog"
url = "blog"
weight = 4
[[Languages.en.menu.main]]
name = "Contact"
url = "contact"
weight = 5
[Languages.ar]
contentDir = "content/arabic"
copyright = "Copyright &copy; 2020 a hugo theme by [themefisher](https://themefisher.com)"
home = "الصفحة الرئيسية"
languageCode = "ar"
languageName = "Ar"
weight = 1
title = "ترينوبيا"
languagedirection = "rtl"
[[Languages.ar.menu.footer]]
name = "teacher"
url = "teacher"
[[Languages.ar.menu.footer]]
name = "notice"
url = "notice"
[[Languages.ar.menu.footer]]
name = "event"
url = "event"
[[Languages.ar.menu.footer]]
name = "scholarship"
url = "scholarship"
[[Languages.ar.menu.footer]]
name = "research"
url = "research"
[[Languages.ar.menu.main]]
name = "من نحن؟"
url = "about"
weight = 1
[[Languages.ar.menu.main]]
name = "برامج الفريق"
url = "course"
weight = 2
[[Languages.ar.menu.main]]
hasChildren = true
name = "خدماتنا"
weight = 3
# [[Languages.ar.menu.main]]
# name = "الفريق"
# parent = "خدماتنا"
# url = "teacher"
# [[Languages.ar.menu.main]]
# name = "تنبيهات"
# parent = "خدماتنا"
# url = "notice"
# [[Languages.ar.menu.main]]
# name = "فعاليات"
# parent = "خدماتنا"
# url = "event"
# [[Languages.ar.menu.main]]
# name = "Cursus"
# parent = "خدماتنا"
# url = "scholarship"
# [[Languages.ar.menu.main]]
# name = "research"
# parent = "خدماتنا"
# url = "research"

[[Languages.ar.menu.main]]
name = "كود فالي"
parent = "خدماتنا"
url = "research"

[[Languages.ar.menu.main]]
name = "ترانوبيا للاطفال و المراهقين"
parent = "خدماتنا"
url = "research"

[[Languages.ar.menu.main]]
name = "يلا كامب"
parent = "خدماتنا"
url = "research"

[[Languages.ar.menu.main]]
name = "معرض الصور"
url = "blog"
weight = 4
[[Languages.ar.menu.main]]
name = "تواصل معنا"
url = "contact"
weight = 5
[params]
address = "1 شارع تونس متفرع من شارع الجزائر، المعادي الجديدة"
author = "Themefisher"
contact_form_action = "#"
description = "This is meta description"
email = "trainopia@gmail.com"
google_analitycs_id = ""
logo = "images/logo.png"
mobile = "+201093802680"
top_header = true
[params.cookies]
enable = true
expire_days = 2
[params.map]
enable = true
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyBu5nZKbeK-WHQ70oqOWo-_4VmwOwKP9YQ"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/animate/animate.css"
[[params.plugins.css]]
link = "plugins/venobox/venobox.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/venobox/venobox.min.js"
[[params.plugins.js]]
link = "plugins/filterizr/jquery.filterizr.min.js"
[[params.plugins.js]]
link = "plugins/google-map/gmap.js"
[params.preloader]
enable = true
preloader = "images/preloader.gif"
[params.subscription]
enable = true
mailchimp_form_action = "https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074"
mailchimp_form_name = "b_463ee871f45d2d93748e77cad_a0a2c6d074"
[[params.social]]
icon = "ti-facebook"
link = "https://www.facebook.com/TrainopiaT.D"
title = "facebook"
# [[params.social]]
# icon = "ti-twitter-alt"
# link = "#"
# title = "twitter"
[[params.social]]
icon = "ti-instagram"
link = "https://www.instagram.com/trainopia_td/"
title = "instagram"
# [[params.social]]
# icon = "ti-github"
# link = "#"
# title = "github"
# [[params.social]]
# icon = "ti-linkedin"
# link = "#"
# title = "linkedin"
